services:
  dev:
    build: .
    container_name: ubuntu2404-os
    volumes:
      - .:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined